name: Build XRPackage
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build package
        id: build
        uses: webaverse/xrpackage-build-action@v0.0.9
        with:
          src: '.'
          dst: 'a.wbn'
      - name: Echo build result
        run: echo 'The output file is ${{ steps.build.outputs.dst }}'
      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@master
        with:
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload release artifact
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args:
          - ${{ steps.build.outputs.dst }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}