name: Build XRPackage
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Build
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Build package
        uses: webaverse/xrpackage-build-action@v0.0.8
        with:
          src: '.'
          dst: 'a.wbn'
        id: build
      # This step prints an output (time) from the previous step's action.
      - name: Echo the output destination file
        run: echo 'The output file is ${{ steps.build.outputs.dst }}'